name: EZRep Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Download NuGet
        run: |
          Invoke-WebRequest -Uri https://dist.nuget.org/win-x64/nuget.exe -OutFile nuget.exe
          $env:PATH += ";$PWD"

      
      - name: Create Build Directory
        run: mkdir _build

      - name: Restore Packages
        run: nuget.exe restore EzRep.sln

      - name: Build and Publish Solution
        run: |
          msbuild.exe DescopeSampleApp.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"

      - name: Build Solution
        run: |
          msbuild.exe DescopeSampleApp.sln /p:platform="Any CPU" /p:configuration="Release"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sampleBundle
          path: _build
