name: Build and Release .NET Framework 4.8 Project

on:
  push:
    tags:
      - 'v*'  # Triggers when pushing a tag that matches v*, e.g., v1.0, v1.0.0
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner for .NET Framework

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore Dependencies
        run: nuget restore

      - name: Build the Project
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" /p:Configuration=Release

      - name: Publish the Project
        run: |
          mkdir publish
          xcopy /s /e /y bin\Release\* publish\

      - name: Archive the Build Artifacts
        run: Compress-Archive -Path ./publish/* -DestinationPath release.zip

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}  # Use the tag name from the trigger (if available)
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifacts to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip
